# Generated by Django 5.1.6 on 2025-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formcode', models.CharField(max_length=100)),
                ('problemdate', models.DateTimeField(null=True)),
                ('machinename', models.CharField(max_length=100)),
                ('machinecode', models.CharField(max_length=100)),
                ('machineplacecode', models.CharField(default='MDF1', max_length=100)),
                ('stoptime', models.DateTimeField(null=True)),
                ('failuretime', models.TimeField(null=True)),
                ('operatorname', models.CharField(max_length=100)),
                ('productionstop', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('suggesttime', models.CharField(max_length=30, null=True)),
                ('worksuggest', models.CharField(max_length=100)),
                ('fixrepair', models.CharField(max_length=100)),
                ('reportinspection', models.CharField(max_length=100)),
                ('faultdm', models.CharField(max_length=100)),
                ('problemdescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
