# Generated by Django 5.1.6 on 2025-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submitform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='faultdm',
            field=models.CharField(default='بازرسی فنی', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
