# Generated by Django 5.1.6 on 2025-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='faultdm',
            field=models.CharField(default='اختلال در کارکرد', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='fixrepair',
            field=models.CharField(default='درخواست اپراتور', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='machinecode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='operatorname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='problemdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='problemdescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='productionstop',
            field=models.CharField(default='خیر', max_length=10),
        ),
        migrations.AddField(
            model_name='submitform',
            name='reportinseption',
            field=models.CharField(default='بازرسی فنی', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='section',
            field=models.CharField(default='Chipper', max_length=30),
        ),
        migrations.AddField(
            model_name='submitform',
            name='shift',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='stoptime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='suggesttime',
            field=models.CharField(default='فوری', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='worksuggest',
            field=models.CharField(default='اضطراری', max_length=50),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('technician', 'Technician')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
