# Generated by Django 5.1.6 on 2025-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submitform_failuretime_submitform_faultdm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitform',
            old_name='reportinseption',
            new_name='reportinspection',
        ),
    ]
