# Generated by Django 5.1.6 on 2025-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_reportinseption_submitform_reportinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='problemdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='stoptime',
            field=models.DateTimeField(null=True),
        ),
    ]
