# Generated by Django 5.1.6 on 2025-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submitform_problemdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='faultdm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='fixrepair',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinecode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(default='MDF1', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='operatorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problemdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='productionstop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='reportinspection',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='shift',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worksuggest',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
