# Generated by Django 5.1.6 on 2025-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
