# Generated by Django 5.1.6 on 2025-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_submitform_failuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'Pm'), ('mechanic', 'Mechanic'), ('production', 'Production'), ('utility', 'Utility'), ('metalworking', 'Metalworking')], max_length=50),
        ),
    ]
