# Generated by Django 5.1.6 on 2025-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(default='Mechanic', max_length=20),
        ),
    ]
