# Generated by Django 5.1.6 on 2025-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'Pm'), ('mechanic', 'Mechanic'), ('production', 'Production'), ('utility', 'Utility'), ('metalworking', 'Metalworking'), ('electric', 'Electric'), ('tarashkari', 'Tarashkari')], default='pm', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
