# Generated by Django 5.1.6 on 2025-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_loginuser_user_type_alter_submitform_formcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(default='mechanic', max_length=20),
        ),
    ]
