# Generated by Django 5.1.6 on 2025-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_submitform_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='phase',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
