# Generated by Django 5.1.6 on 2025-03-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_submitform_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(default='01', max_length=100, null=True),
        ),
    ]
