# Generated by Django 5.1.6 on 2025-03-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_submitform_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
