# Generated by Django 5.1.6 on 2025-03-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_submitform_machineplacecode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aghlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalaname', models.CharField(max_length=50)),
                ('countkala', models.CharField(max_length=50)),
                ('vahedkala', models.CharField(max_length=50)),
                ('codekala', models.CharField(max_length=50)),
                ('flamekala', models.CharField(max_length=50)),
                ('shopkala', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianPersonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel', models.CharField(max_length=50)),
                ('personelnumber', models.CharField(max_length=50)),
                ('datesubmit', models.DateTimeField(null=True)),
                ('specialjob', models.CharField(max_length=50)),
                ('starttimerepair', models.DateTimeField(null=True)),
                ('endtimerepair', models.DateTimeField(null=True)),
                ('repairstatus', models.CharField(max_length=50)),
                ('unitrepair', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
                ('delayreason', models.CharField(max_length=50)),
                ('failurereason', models.CharField(max_length=50)),
                ('failurereasondescription', models.CharField(max_length=50)),
                ('suggestionfailure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failurepart', models.CharField(max_length=50)),
                ('failuretime', models.DateTimeField(null=True)),
                ('sparetime', models.DateTimeField(null=True)),
                ('startfailuretime', models.DateTimeField(null=True)),
                ('problemdescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
