# Generated by Django 5.1.6 on 2025-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_techniciansubmit_formcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicianpersonel',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
