# Generated by Django 5.1.6 on 2025-03-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_aghlam_formcode_technicianpersonel_formcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aghlams', to='api.submitform'),
        ),
    ]
