# Generated by Django 5.1.6 on 2025-03-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_aghlam_submit_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianpersonel',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personels', to='api.submitform'),
        ),
    ]
