# Generated by Django 5.1.6 on 2025-03-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_technicianpersonel_submit_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciansubmit',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_submits', to='api.submitform'),
        ),
        migrations.AlterField(
            model_name='technicianpersonel',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_personels', to='api.submitform'),
        ),
    ]
