# Generated by Django 5.1.6 on 2025-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_submitform_operator_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciansubmit',
            name='jobstatus',
            field=models.CharField(default='بله', max_length=20),
        ),
    ]
