# Generated by Django 5.1.6 on 2025-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_submitform_jobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitform',
            name='jobstatus',
        ),
    ]
