# Generated by Django 5.1.6 on 2025-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_submitform_jobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitform',
            name='operator_submitted',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='technician_status',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='technician_submitted',
        ),
        migrations.AddField(
            model_name='techniciansubmit',
            name='technician_status',
            field=models.CharField(choices=[('pending', 'درحال انتظار برای ثبت تکنیسین'), ('reviewed', 'فرم توسط تکنیسین بررسی شد'), ('returned', 'فرم برگشت داده شد')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='techniciansubmit',
            name='technician_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='jobstatus',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
