# Generated by Django 5.1.6 on 2025-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_submitform_operator_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciansubmit',
            name='technician_status',
        ),
        migrations.RemoveField(
            model_name='techniciansubmit',
            name='technician_submitted',
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='jobstatus',
            field=models.CharField(default='در حال انجام', max_length=20),
        ),
    ]
