# Generated by Django 5.1.6 on 2025-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_techniciansubmit_technician_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='operator_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitform',
            name='technician_status',
            field=models.CharField(choices=[('pending', 'درحال انتظار برای ثبت تکنیسین'), ('reviewed', 'فرم توسط تکنیسین بررسی شد'), ('returned', 'فرم برگشت داده شد')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='submitform',
            name='technician_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='jobstatus',
            field=models.CharField(choices=[('بله', 'کار انجام شد'), ('خیر', 'کار انجام نشد'), ('در حال انجام', 'در حال انجام')], default='در حال انجام', max_length=20),
        ),
    ]
