# Generated by Django 5.1.6 on 2025-03-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_techniciansubmit_jobstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicianPersonel',
            new_name='Personel',
        ),
    ]
