# Generated by Django 5.1.6 on 2025-03-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_aghlam_submit_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciansubmit',
            name='submit_form',
        ),
    ]
