# Generated by Django 5.1.6 on 2025-03-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_techniciansubmit_submit_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personel', to='api.submitform'),
        ),
        migrations.AddField(
            model_name='techniciansubmit',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_submits', to='api.submitform'),
        ),
    ]
