# Generated by Django 5.1.6 on 2025-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_personel_submit_form_techniciansubmit_submit_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
    ]
