# Generated by Django 5.1.6 on 2025-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_submitform_failuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciansubmit',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='sparetime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='startfailuretime',
            field=models.TimeField(null=True),
        ),
    ]
