# Generated by Django 4.2.7 on 2025-04-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_techniciansubmit_failuretime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aghlam', to='api.submitform'),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='submit_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_submit', to='api.submitform'),
        ),
    ]
