# Generated by Django 5.1.6 on 2025-04-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_aghlam_submit_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='formtype',
            field=models.CharField(default='pm', max_length=20),
        ),
    ]
