# Generated by Django 5.1.6 on 2025-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_submitform_formtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(default='pm', max_length=20),
        ),
    ]
