# Generated by Django 5.1.6 on 2025-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(max_length=20),
        ),
    ]
