# Generated by Django 5.1.6 on 2025-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
