# Generated by Django 5.1.6 on 2025-04-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_submitform_failuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
