# Generated by Django 5.1.6 on 2025-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_submitform_failuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciansubmit',
            name='failuretime',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
