# Generated by Django 5.1.6 on 2025-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_techniciansubmit_failuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciansubmit',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='startfailuretime',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
