# Generated by Django 4.2.7 on 2025-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_techniciansubmit_failuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='formtype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
