# Generated by Django 4.2.7 on 2025-04-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_submitform_formtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitform',
            options={'ordering': ['-problemdate']},
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='operator_submitted',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='technician_status',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='technician_submitted',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='sub_user_type',
            field=models.CharField(choices=[('management', 'Management'), ('technician', 'Technician'), ('operator', 'Operator')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='assigned_department',
            field=models.CharField(choices=[('pm', 'Pm'), ('mechanic', 'Mechanic'), ('production', 'Production'), ('utility', 'Utility'), ('metalworking', 'Metalworking'), ('electric', 'Electric'), ('tarashkari', 'Tarashkari')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitform',
            name='current_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitform',
            name='status',
            field=models.CharField(choices=[('pending_technician', 'Pending Technician Review'), ('technician_submitted', 'Technician Submitted'), ('pending_management', 'Pending Management Approval'), ('management_approved', 'Management Approved'), ('pending_production', 'Pending Production Confirmation'), ('production_confirmed', 'Production Confirmed'), ('pending_pm', 'Pending PM Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_technician', max_length=50),
        ),
    ]
