# Generated by Django 4.2.7 on 2025-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_submitform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='sub_user_type',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('management', 'Management'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'PM'), ('production', 'Production'), ('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='loginuser',
            table='login_user',
        ),
    ]
