# Generated by Django 4.2.7 on 2025-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_submitform_formcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
