# Generated by Django 4.2.7 on 2025-04-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_formcode_unique'),
        ('api', '0055_alter_submitform_formcode'),
    ]

    operations = [
    ]
