# Generated by Django 5.1.6 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_merge_20250407_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitform',
            options={'ordering': ['problemdate']},
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
