# Generated by Django 5.1.6 on 2025-04-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_submitform_options_alter_submitform_formcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitform',
            options={'ordering': ['-problemdate']},
        ),
    ]
