# Generated by Django 4.2.7 on 2025-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_submitform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciansubmit',
            name='failuretime',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='techniciansubmit',
            name='sparetime',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
