# Generated by Django 5.1.6 on 2025-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_techniciansubmit_failuretime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
    ]
