# Generated by Django 4.2.7 on 2025-04-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_personel_datesubmit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aghlam',
            name='flamekala',
        ),
    ]
