# Generated by Django 4.2.7 on 2025-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_aghlam_flamekala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aghlam',
            name='shopkala',
        ),
        migrations.AddField(
            model_name='aghlam',
            name='flamekala',
            field=models.CharField(default='خیر', max_length=50),
            preserve_default=False,
        ),
    ]
