# Generated by Django 4.2.7 on 2025-04-09 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_aghlam_shopkala_aghlam_flamekala'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submitform',
            name='endtime_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='faultdm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='fixrepair',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinecode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='operatorname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='phase',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problemdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problemdescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='productionstop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='reportinspection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='stoptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worksuggest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worktype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
