# Generated by Django 4.2.7 on 2025-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_submitform_created_at_submitform_endtime_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='productionstop',
            field=models.CharField(default='خیر', max_length=10),
        ),
    ]
