# Generated by Django 5.1.6 on 2025-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='phase',
            field=models.CharField(choices=[('phase1', 'Phase 1'), ('phase2', 'Phase 2')], default='phase1', max_length=10),
        ),
    ]
