# Generated by Django 5.1.6 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_loginuser_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='section',
            field=models.CharField(choices=[('Chipper', 'Chipper'), ('Conveyor Line', 'Conveyor Line'), ('Dryer & Air Grader', 'Dryer & Air Grader'), ('Refiner', 'Refiner'), ('Before Press', 'Before Press'), ('Press', 'Press'), ('After Press', 'After Press'), ('Sanding', 'Sanding'), ('Cooling System', 'Cooling System'), ('Steam Boiler', 'Steam Boiler'), ('General', 'General'), ('Melamine', 'Melamine'), ('High Glass', 'High Glass'), ('Formalin', 'Formalin'), ('Resin', 'Resin'), ('Purification Plant', 'Purification Plant'), ('Agheshte', 'Agheshte')], default='General', max_length=50),
        ),
    ]
