# Generated by Django 5.1.6 on 2025-04-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_loginuser_sections_loginuser_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='section',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='sections',
            field=models.ManyToManyField(related_name='users', to='api.section'),
        ),
    ]
