# Generated by Django 5.1.6 on 2025-04-10 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_section_remove_loginuser_section_loginuser_sections'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='loginuser',
            constraint=models.UniqueConstraint(fields=('username', 'user_type'), name='unique_username_per_type'),
        ),
    ]
