# Generated by Django 5.1.6 on 2025-04-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_loginuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loginuser',
            name='unique_username_per_type',
        ),
    ]
