# Generated by Django 5.1.6 on 2025-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_loginuser_unique_username_per_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='sections',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='sections',
            field=models.JSONField(default=list),
        ),
    ]
