# Generated by Django 4.2.7 on 2025-04-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_remove_loginuser_sections_loginuser_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='phase',
        ),
    ]
