# Generated by Django 4.2.7 on 2025-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_loginuser_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
