# Generated by Django 4.2.7 on 2025-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_loginuser_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'PM'), ('production', 'Production'), ('generalmechanic', 'General Mechanic'), ('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari')], max_length=20),
        ),
    ]
