# Generated by Django 4.2.7 on 2025-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='management_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='operator_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='pm_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='production_management_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='technician_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
