# Generated by Django 5.2 on 2025-04-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_loginuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='status',
            field=models.CharField(choices=[('pending_technician', 'Pending Technician Review'), ('technician_submitted', 'Technician Submitted'), ('pending_management', 'Pending Management Approval'), ('management_approved', 'Management Approved'), ('pending_production', 'Pending Production Confirmation'), ('production_confirmed', 'Production Confirmed'), ('production_management_confirm', 'Production Management Confirmed'), ('pending_pm', 'Pending PM Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_technician', max_length=50),
        ),
    ]
