# Generated by Django 5.2 on 2025-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_personel_endtimerepair2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='testfield',
            field=models.CharField(default='', max_length=50),
        ),
    ]
