# Generated by Django 5.2 on 2025-04-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_personel_testfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personel',
            old_name='testfield',
            new_name='personel2',
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair6',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair7',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='endtimerepair8',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='personelnumber8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='specialjob8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair6',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair7',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='starttimerepair8',
            field=models.DateTimeField(null=True),
        ),
    ]
