# Generated by Django 5.2 on 2025-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_testfield_personel_personel2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'PM'), ('production', 'Production'), ('generalmechanic', 'General Mechanic'), ('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility')], max_length=20),
        ),
    ]
