# Generated by Django 5.2 on 2025-04-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_loginuser_additional_roles_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('pm', 'PM'), ('production', 'Production'), ('generalmechanic', 'General Mechanic'), ('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], max_length=20),
        ),
    ]
