# Generated by Django 5.2 on 2025-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='status',
            field=models.CharField(choices=[('pending_technician', 'Pending Technician Review'), ('technician_submitted', 'Technician Submitted'), ('pending_management', 'Pending Management Approval'), ('management_approved', 'Management Approved'), ('pending_production', 'Pending Production Confirmation'), ('production_confirmed', 'Production Confirmed'), ('production_management_confirm', 'Production Management Confirmed'), ('pm_technician_pending', 'Pending Technician PM Send to Management'), ('pending_pm', 'Pending PM Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_technician', max_length=50),
        ),
    ]
