# Generated by Django 5.2 on 2025-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_submitform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], default='', max_length=50, null=True),
        ),
    ]
