# Generated by Django 5.2 on 2025-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_submitform_assigned_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formcode', models.CharField(blank=True, default='', max_length=10, null=True, unique=True)),
                ('pmformdate', models.DateTimeField(blank=True, null=True)),
                ('unitname', models.CharField(max_length=20)),
                ('worktype', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=30)),
                ('machinename', models.CharField(max_length=30)),
                ('pmsubject', models.CharField(max_length=100)),
            ],
        ),
    ]
