# Generated by Django 5.2 on 2025-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_pmforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='phase',
            field=models.CharField(default='01', max_length=2),
        ),
    ]
