# Generated by Django 5.2 on 2025-04-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_pmforms_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciansubmit',
            name='submit_form',
        ),
        migrations.AddField(
            model_name='techniciansubmit',
            name='pm_submit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_submit', to='api.pmforms'),
        ),
        migrations.CreateModel(
            name='PmAghlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formcode', models.CharField(max_length=100, null=True)),
                ('kalaname', models.CharField(max_length=50)),
                ('countkala', models.CharField(max_length=50)),
                ('vahedkala', models.CharField(max_length=50)),
                ('codekala', models.CharField(max_length=50)),
                ('flamekala', models.CharField(max_length=50)),
                ('pm_submit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aghlam', to='api.pmforms')),
            ],
        ),
        migrations.CreateModel(
            name='PmTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formcode', models.CharField(max_length=100, null=True)),
                ('failurereason', models.CharField(max_length=100)),
                ('worktypepm', models.CharField(max_length=50)),
                ('pmproblemdescription', models.TextField(blank=True, null=True)),
                ('startpmrepairtime', models.DateTimeField(blank=True, null=True)),
                ('endpmrepairtime', models.DateTimeField(blank=True, null=True)),
                ('worktime', models.CharField(max_length=50)),
                ('notdonereason', models.CharField(max_length=50)),
                ('pm_submit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='api.pmforms')),
            ],
        ),
    ]
