# Generated by Django 5.2 on 2025-04-15 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_remove_techniciansubmit_submit_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmforms',
            options={'ordering': ['-pmformdate']},
        ),
        migrations.AddField(
            model_name='pmforms',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pm_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='current_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pm_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='management_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='operator_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='pm_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='production_management_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='status',
            field=models.CharField(choices=[('pending_technician', 'Pending Technician Review'), ('technician_submitted', 'Technician Submitted'), ('pending_management', 'Pending Management Approval'), ('management_approved', 'Management Approved'), ('pending_production', 'Pending Production Confirmation'), ('production_confirmed', 'Production Confirmed'), ('production_management_confirm', 'Production Management Confirmed'), ('pending_pm', 'Pending PM Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_technician', max_length=50),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='technician_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pmforms',
            name='worktype',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], max_length=20),
        ),
    ]
