# Generated by Django 5.2 on 2025-04-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_pmforms_options_pmforms_assigned_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmforms',
            options={'verbose_name': 'PM Form', 'verbose_name_plural': 'PM Forms'},
        ),
    ]
