# Generated by Django 4.2.7 on 2025-04-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_pmforms_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmforms',
            old_name='status',
            new_name='pmstatus',
        ),
    ]
