# Generated by Django 4.2.7 on 2025-04-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_rename_status_pmforms_pmstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmforms',
            old_name='worktype',
            new_name='pmworktype',
        ),
    ]
