# Generated by Django 4.2.7 on 2025-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_rename_worktype_pmforms_pmworktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmforms',
            old_name='machinename',
            new_name='pmmachinename',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='phase',
            new_name='pmphase',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='section',
            new_name='pmsection',
        ),
    ]
