# Generated by Django 4.2.7 on 2025-04-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_rename_machinename_pmforms_pmmachinename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmaghlam',
            old_name='formcode',
            new_name='pmformcode',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='formcode',
            new_name='pmformcode',
        ),
        migrations.RenameField(
            model_name='pmtechnician',
            old_name='formcode',
            new_name='pmformcode',
        ),
    ]
