# Generated by Django 4.2.7 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_rename_formcode_pmaghlam_pmformcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmforms',
            old_name='management_confirmation_date',
            new_name='final_pm_management_confirmation_date',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='operator_confirmation_date',
            new_name='final_pm_technician_confirmation_date',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pmformcode',
            new_name='formcode',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pmmachinename',
            new_name='machinename',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pmphase',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pm_confirmation_date',
            new_name='pm_management_confirmation_date',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='technician_confirmation_date',
            new_name='pm_technician_confirmation_date',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pmsection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='pmworktype',
            new_name='worktype',
        ),
        migrations.RemoveField(
            model_name='pmforms',
            name='pmstatus',
        ),
        migrations.AddField(
            model_name='pmforms',
            name='production_operator_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='status',
            field=models.CharField(choices=[('pending_pm_technician', 'Pending PM Technician Review'), ('pending_pm_management', 'Pending PM Management First Review'), ('pending_worktype_technician', 'Pending Worktype Technician Review'), ('worktype_technician_submitted', 'Worktype Technician Submitted'), ('pending_worktype_management', 'Pending Worktype Management Approval'), ('worktype_management_approved', 'Worktype Management Approved'), ('pending_production_operator', 'Pending Production Operator'), ('production_operator_confirmed', 'Production Operator Confirmed'), ('pending_production_management', 'Pending Production Management'), ('production_management_confirmed', 'Production Management Confirmed'), ('pending_final_pm_technician', 'Pending Final PM Technician Review'), ('pending_final_pm_management', 'Pending Final PM Management Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_pm_technician', max_length=50),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='worktype_management_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='worktype_technician_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
