# Generated by Django 4.2.7 on 2025-04-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_rename_management_confirmation_date_pmforms_final_pm_management_confirmation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmforms',
            old_name='formcode',
            new_name='pmformcode',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='machinename',
            new_name='pmmachinename',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='phase',
            new_name='pmphase',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='section',
            new_name='pmsection',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='status',
            new_name='pmstatus',
        ),
        migrations.RenameField(
            model_name='pmforms',
            old_name='worktype',
            new_name='pmworktype',
        ),
    ]
