# Generated by Django 5.1.6 on 2025-04-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_rename_formcode_pmforms_pmformcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmPersonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmformcode', models.CharField(max_length=100, null=True)),
                ('personel', models.CharField(max_length=50)),
                ('personelnumber', models.CharField(max_length=50)),
                ('specialjob', models.CharField(max_length=50)),
                ('starttimerepair', models.DateTimeField(null=True)),
                ('endtimerepair', models.DateTimeField(null=True)),
                ('personel2', models.CharField(default='', max_length=50)),
                ('personelnumber2', models.CharField(default='', max_length=50)),
                ('specialjob2', models.CharField(default='', max_length=50)),
                ('starttimerepair2', models.DateTimeField(null=True)),
                ('endtimerepair2', models.DateTimeField(null=True)),
                ('personel3', models.CharField(default='', max_length=50)),
                ('personelnumber3', models.CharField(default='', max_length=50)),
                ('specialjob3', models.CharField(default='', max_length=50)),
                ('starttimerepair3', models.DateTimeField(null=True)),
                ('endtimerepair3', models.DateTimeField(null=True)),
                ('personel4', models.CharField(default='', max_length=50)),
                ('personelnumber4', models.CharField(default='', max_length=50)),
                ('specialjob4', models.CharField(default='', max_length=50)),
                ('starttimerepair4', models.DateTimeField(null=True)),
                ('endtimerepair4', models.DateTimeField(null=True)),
                ('personel5', models.CharField(default='', max_length=50)),
                ('personelnumber5', models.CharField(default='', max_length=50)),
                ('specialjob5', models.CharField(default='', max_length=50)),
                ('starttimerepair5', models.DateTimeField(null=True)),
                ('endtimerepair5', models.DateTimeField(null=True)),
                ('personel6', models.CharField(default='', max_length=50)),
                ('personelnumber6', models.CharField(default='', max_length=50)),
                ('specialjob6', models.CharField(default='', max_length=50)),
                ('starttimerepair6', models.DateTimeField(null=True)),
                ('endtimerepair6', models.DateTimeField(null=True)),
                ('personel7', models.CharField(default='', max_length=50)),
                ('personelnumber7', models.CharField(default='', max_length=50)),
                ('specialjob7', models.CharField(default='', max_length=50)),
                ('starttimerepair7', models.DateTimeField(null=True)),
                ('endtimerepair7', models.DateTimeField(null=True)),
                ('personel8', models.CharField(default='', max_length=50)),
                ('personelnumber8', models.CharField(default='', max_length=50)),
                ('specialjob8', models.CharField(default='', max_length=50)),
                ('starttimerepair8', models.DateTimeField(null=True)),
                ('endtimerepair8', models.DateTimeField(null=True)),
                ('repairstatus', models.CharField(max_length=50)),
                ('unitrepair', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
                ('delayreason', models.CharField(max_length=50)),
                ('failurereason', models.CharField(max_length=50)),
                ('failurereasondescription', models.CharField(max_length=50)),
                ('suggestionfailure', models.CharField(max_length=50)),
                ('pm_submit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personel', to='api.pmforms')),
            ],
        ),
    ]
