# Generated by Django 5.1.6 on 2025-04-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_pmpersonel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmtechnician',
            name='pmjobstatus',
            field=models.CharField(choices=[('بله', 'کار انجام شد'), ('خیر', 'کار انجام نشد'), ('در حال انجام', 'در حال انجام')], default='کار انجام شد', max_length=20),
        ),
        migrations.AddField(
            model_name='pmtechnician',
            name='pmrepairstatus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
