# Generated by Django 5.1.6 on 2025-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_pmtechnician_pmjobstatus_pmtechnician_pmrepairstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmtechnician',
            name='pmrepairstatus',
        ),
    ]
