# Generated by Django 5.1.6 on 2025-04-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_remove_pmtechnician_pmrepairstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmaghlam',
            name='flamekala',
        ),
    ]
