# Generated by Django 5.1.6 on 2025-04-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_remove_pmaghlam_flamekala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmtechnician',
            old_name='failurereason',
            new_name='pmfailurereason',
        ),
    ]
