# Generated by Django 5.1.6 on 2025-04-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_rename_failurereason_pmtechnician_pmfailurereason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmtechnician',
            old_name='worktypepm',
            new_name='pmworktype',
        ),
    ]
