# Generated by Django 4.2.7 on 2025-04-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_rename_worktypepm_pmtechnician_pmworktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmforms',
            name='unitname',
        ),
    ]
