# Generated by Django 4.2.7 on 2025-04-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_remove_pmforms_unitname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmpersonel',
            name='delayreason',
        ),
        migrations.RemoveField(
            model_name='pmpersonel',
            name='failurereason',
        ),
        migrations.RemoveField(
            model_name='pmpersonel',
            name='suggestionfailure',
        ),
    ]
