# Generated by Django 5.1.6 on 2025-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_remove_pmpersonel_delayreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='unitname',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pmforms',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('generalmechanic', 'General Mechanic'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pmforms',
            name='pmworktype',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('generalmechanic', 'General Mechanic'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], max_length=20),
        ),
    ]
