# Generated by Django 5.1.6 on 2025-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_pmforms_unitname_alter_pmforms_assigned_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmpersonel',
            name='failurereasondescription',
        ),
    ]
