# Generated by Django 5.2 on 2025-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_remove_pmpersonel_repairstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='formnote',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
