# Generated by Django 4.2.7 on 2025-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_submitform_formnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='pmformnote',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
