# Generated by Django 4.2.7 on 2025-04-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_pmforms_pmformnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='assigned_department',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('generalmechanic', 'General Mechanic'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], default='', max_length=50, null=True),
        ),
    ]
