# Generated by Django 5.2 on 2025-04-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_alter_submitform_assigned_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='management_confirmation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='submitform',
            name='operator_confirmation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='submitform',
            name='pm_confirmation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='submitform',
            name='production_management_confirmation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='submitform',
            name='technician_confirmation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
