# Generated by Django 5.2 on 2025-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_submitform_management_confirmation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='operator_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='pm_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='production_management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='technician_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
