# Generated by Django 5.2 on 2025-04-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_alter_submitform_management_confirmation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitform',
            old_name='failuretime',
            new_name='failuretimesubmit',
        ),
    ]
