# Generated by Django 4.2.7 on 2025-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_rename_failuretime_submitform_failuretimesubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='final_pm_management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='final_pm_technician_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='pm_management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='pm_technician_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='production_management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='production_operator_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='worktype_management_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmforms',
            name='worktype_technician_confirmation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
