# Generated by Django 5.2 on 2025-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_pmforms_final_pm_management_confirmation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='stoptype',
            field=models.CharField(default='تجهیز', max_length=50),
            preserve_default=False,
        ),
    ]
