# Generated by Django 4.2.7 on 2025-04-28 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_submitform_stoptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='formnote_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitform',
            name='formnote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formnotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
