# Generated by Django 5.2 on 2025-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_submitform_formnote_edited_submitform_formnote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciansubmit',
            name='wastedtime',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
