# Generated by Django 5.2 on 2025-05-28 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_techniciansubmit_wastedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/title of the reminder', max_length=200)),
                ('datetime', models.DateTimeField(help_text='Date and time for the reminder')),
                ('phoneNumber', models.CharField(help_text='Phone number to send SMS to', max_length=20)),
                ('workType', models.CharField(choices=[('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Inspection', 'Inspection'), ('Emergency', 'Emergency'), ('Consultation', 'Consultation'), ('Training', 'Training'), ('Other', 'Other')], help_text='Type of work for this reminder', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether SMS has been sent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['datetime'],
            },
        ),
    ]
