# Generated by Django 4.2.7 on 2025-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='reminder',
            name='phoneNumbers',
            field=models.JSONField(default=list, help_text='List of phone numbers to send SMS to'),
        ),
    ]
