# Generated by Django 5.2.5 on 2025-08-27 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_remove_reminder_phonenumber_reminder_phonenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default='', max_length=50)),
                ('tarikhe_sabt', models.DateTimeField()),
                ('ghesmat', models.CharField(default='', max_length=255)),
                ('mozu', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
