# Generated by Django 5.2.5 on 2025-08-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_watertreatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watertreatment',
            old_name='tarikhe_sabt',
            new_name='tarikhesabt',
        ),
    ]
