# Generated by Django 5.2.5 on 2025-08-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_rename_tarikhe_sabt_watertreatment_tarikhesabt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watertreatment',
            options={'ordering': ['-tarikhesabt'], 'verbose_name': 'Water Treatment Record', 'verbose_name_plural': 'Water Treatment Records'},
        ),
        migrations.AddField(
            model_name='watertreatment',
            name='shift',
            field=models.CharField(default='', help_text='شیفت کاری', max_length=5),
        ),
        migrations.AddField(
            model_name='watertreatment',
            name='value',
            field=models.CharField(default='', help_text='مقدار اندازه گیری شده', max_length=255),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='ghesmat',
            field=models.CharField(default='', help_text='قسمت مربوطه', max_length=255),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='mozu',
            field=models.CharField(default='', help_text='موضوع', max_length=255),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='operator',
            field=models.CharField(default='', help_text='نام اپراتور', max_length=100),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='tarikhesabt',
            field=models.DateTimeField(blank=True, help_text='تاریخ و ساعت ثبت فرم', null=True),
        ),
    ]
