# Generated by Django 5.2.5 on 2025-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_alter_watertreatment_options_watertreatment_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertreatment',
            name='mozu',
            field=models.CharField(blank=True, default='', help_text='موضوع', max_length=255),
        ),
    ]
