# Generated by Django 5.2.5 on 2025-10-27 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_alter_watertreatment_mozu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmsubmitdate', models.DateTimeField(blank=True, null=True)),
                ('pmserial', models.CharField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('pmsection', models.CharField(blank=True, default='', max_length=100)),
                ('pmsubject', models.CharField(blank=True, default='', max_length=250)),
                ('pmworktype', models.CharField(blank=True, default='', max_length=100)),
                ('pmstatus', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submit_pm', to=settings.AUTH_USER_MODEL)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submit_pm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submit PM',
                'verbose_name_plural': 'Submit PMs',
                'ordering': ['-pmserial', '-created_at'],
            },
        ),
    ]
