# Generated by Django 5.2.5 on 2025-10-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_submitpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitpm',
            name='pmserial',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
