# Generated by Django 5.2.8 on 2025-11-27 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_alter_submitpm_pmserial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(choices=[('پاک چوب خوزستان', 'پاک چوب خوزستان'), ('پاک چوب ایرانیان', 'پاک چوب ایرانیان'), ('پاک چوب خراسان', 'پاک چوب خراسان'), ('پاک چوب تخته فشرده', 'پاک چوب تخته فشرده'), ('گروه صنعتی', 'گروه صنعتی')], max_length=100)),
                ('section', models.CharField(choices=[('PM', 'PM'), ('Production', 'Production'), ('QC', 'QC'), ('Financial', 'Financial'), ('Human Resources', 'Human Resources'), ('HSE', 'HSE'), ('WareHouse', 'WareHouse'), ('Security', 'Security'), ('Sales', 'Sales')], max_length=100)),
                ('role', models.CharField(choices=[('مدیر', 'مدیر'), ('رئیس', 'رئیس'), ('کارشناس', 'کارشناس')], max_length=50)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Done', 'کار انجام شد'), ('Working', 'در حال انجام'), ('Not Done', 'کار انجام نشده')], default='Working', max_length=20)),
                ('percentage', models.IntegerField(default=0, help_text='Completion percentage 0-100')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_work_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Work',
                'verbose_name_plural': 'KPI Works',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', '-created_at'], name='api_kpiwork_person__a055d2_idx'), models.Index(fields=['facility', 'section'], name='api_kpiwork_facilit_df2c95_idx')],
            },
        ),
    ]
