# Generated by Django 5.2.8 on 2025-11-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_kpiwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIWorkResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="User's response/answer to the work")),
                ('completion_notes', models.TextField(blank=True, help_text='Completion notes', null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs or file references')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('completed', 'Completed'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.kpiwork')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Work Response',
                'verbose_name_plural': 'KPI Work Responses',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['kpi_work', '-submitted_at'], name='api_kpiwork_kpi_wor_3ebdf5_idx'), models.Index(fields=['respondent', 'status'], name='api_kpiwork_respond_302fba_idx')],
            },
        ),
    ]
