# Generated by Django 5.2.8 on 2025-11-28 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_kpiworkresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIEntry',
            fields=[
                ('row', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='company_name')),
                ('season', models.CharField(blank=True, max_length=50, verbose_name='season')),
                ('personal_code', models.CharField(blank=True, max_length=50, verbose_name='personal code')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='full name')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='role')),
                ('direct_management', models.CharField(blank=True, max_length=200, verbose_name='direct management')),
                ('departman', models.CharField(blank=True, max_length=200, verbose_name='departman')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='categoty')),
                ('obj_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='obj weight')),
                ('kpi_en', models.CharField(blank=True, max_length=250, verbose_name='KPI En')),
                ('kpi_fa', models.CharField(blank=True, max_length=250, verbose_name='KPI Fa')),
                ('kpi_info', models.TextField(blank=True, verbose_name='kpi info')),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='target')),
                ('kpi_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='KPI Weight')),
                ('kpi_achievement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='KPI Achievement')),
                ('score_achievement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='score Achievement')),
                ('score_achievement_alt', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Score Achievement')),
                ('entry_type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('sum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Sum')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Entry',
                'verbose_name_plural': 'KPI Entries',
                'ordering': ['-row'],
            },
        ),
    ]
