# Generated by Django 5.2.8 on 2025-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_kpientry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiwork',
            name='section',
            field=models.CharField(choices=[('Plant Maintenance', 'Plant Maintenance'), ('Production', 'Production'), ('QC', 'QC'), ('Financial', 'Financial'), ('Human Resources', 'Human Resources'), ('HSE', 'HSE'), ('WareHouse', 'WareHouse'), ('Security', 'Security'), ('Sales', 'Sales')], max_length=100),
        ),
    ]
