# Generated by Django 5.2.8 on 2025-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('management', 'Management'), ('manager', 'Manager'), ('superadmin', 'SuperAdmin'), ('technician', 'Technician'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('ceo', 'CEO'), ('management', 'Management'), ('manager', 'Manager'), ('superadmin', 'SuperAdmin'), ('pm', 'PM'), ('production', 'Production'), ('generalmechanic', 'General Mechanic'), ('mechanic', 'Mechanic'), ('electric', 'Electric'), ('utility', 'Utility'), ('metalworking', 'Metal Working'), ('tarashkari', 'Tarash Kari'), ('paint', 'Paint')], max_length=20),
        ),
    ]
