# Generated by Django 5.2.8 on 2025-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_alter_loginuser_role_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='departman',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='direct_management',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='kpi_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='personal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='season',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
