# Generated by Django 5.2.8 on 2025-12-06 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_kpipersonel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQ2Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('season', models.CharField(blank=True, default='', max_length=50)),
                ('personal_code', models.CharField(blank=True, default='', max_length=50)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('direct_manager_code', models.CharField(blank=True, default='', max_length=50)),
                ('manager_name', models.CharField(blank=True, default='', max_length=200)),
                ('departman', models.CharField(blank=True, default='', max_length=200)),
                ('category_fa', models.CharField(blank=True, default='', max_length=200)),
                ('category_en', models.CharField(blank=True, default='', max_length=200)),
                ('obj_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('kpi_en', models.CharField(blank=True, default='', max_length=250)),
                ('kpi_fa', models.CharField(blank=True, default='', max_length=250)),
                ('kpi_info', models.TextField(blank=True, default='')),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('kpi_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('kpi_achievement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('percentage_achievement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('score_achievement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('entry_type', models.CharField(blank=True, default='', max_length=100)),
                ('sum_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Q2 Entry',
                'verbose_name_plural': 'Group Q2 Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
