# Generated by Django 5.2.8 on 2025-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_groupq2entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupq2entry',
            name='kpi_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='groupq2entry',
            name='kpi_fa',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
