# Generated by Django 5.2.8 on 2025-12-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_alter_groupq2entry_kpi_en_alter_groupq2entry_kpi_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupq2entry',
            name='direct_management2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groupq2entry',
            name='direct_management2_personal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
