# Generated by Django 5.2.8 on 2025-12-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_groupq2entry_direct_management2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupq2entry',
            name='direct_management2',
        ),
        migrations.RemoveField(
            model_name='groupq2entry',
            name='direct_management2_personal_code',
        ),
    ]
